name: CI

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: cd ${{ secrets.PATH_API_DEV }} && git pull && npm install && pm2 restart