name: CI

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: [ubuntu-latest]

    steps:
      - name: SSH and deploy node app
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            KEY: ${{ secrets.SSHKEY }}
            port: ${{ secrets.PORT }}
            script: |
              cd ${{ secrets.PATH_API_DEV }}
              git pull development
              npm install --production
              pm2 restart node-app